name: juntapay
description: Split your payment's with the JuntaPay app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get: ^4.6.1
  intl: ^0.17.0
  brasil_fields: ^1.3.0
  uuid: ^3.0.5
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^5.0.17
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg