name: juntapay
description: Split your payment's with the JuntaPay app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  get: ^4.6.1
  responsive_framework: ^0.1.5
  intl: ^0.17.0
  brasil_fields: ^1.3.0
  uuid: ^3.0.5
  shared_preferences: ^2.0.11
  package_info_plus: ^1.3.0
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.4
  drift: ^1.2.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.1
  path_provider: ^2.0.8
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^5.0.17
  build_runner: ^2.1.7
  drift_dev: ^1.2.0
  test:

flutter:
  uses-material-design: true

  # assets:
  #   - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/thin.ttf
          weight: 100
        - asset: assets/fonts/inter/light.ttf
          weight: 300
        - asset: assets/fonts/inter/regular.ttf
          weight: 400
        - asset: assets/fonts/inter/medium.ttf
          weight: 500
        - asset: assets/fonts/inter/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter/bold.ttf
          weight: 700

    # Icones

    - family: JuntaPay
      fonts:
        - asset: assets/icons/JuntaPay.ttf