name: juntapay
description: Split your payment's with the JuntaPay app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get: ^4.6.1
  responsive_framework: ^0.1.5
  intl: ^0.17.0
  brasil_fields: ^1.3.0
  uuid: ^3.0.5
  package_info_plus: ^1.3.0
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.4
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^5.0.17
  build_runner: ^2.1.7
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/thin.ttf
          weight: 100
        - asset: assets/fonts/inter/light.ttf
          weight: 300
        - asset: assets/fonts/inter/regular.ttf
          weight: 400
        - asset: assets/fonts/inter/medium.ttf
          weight: 500
        - asset: assets/fonts/inter/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter/bold.ttf
          weight: 700